compact_str/src/lib.rs, compact_str/src/tests.rs
=> Add impl PartialEq<CompactStr> for &str

CHANGELOG.md, README.md, compact_str/Cargo.toml
=> Bump version to 0.1.2

.github/workflows/ci.yml, .github/workflows/clippy.yml, .github/workflows/cross_platform.yml, .github/workflows/msrv.yml
This PR just re-organizes CI builds a bit
=> Reorganize CI Builds

compact_str/benches/apis.rs, compact_str/src/lib.rs, compact_str/src/repr/heap/arc.rs, compact_str/src/repr/heap/mod.rs, compact_str/src/repr/inline.rs, compact_str/src/repr/mod.rs, compact_str/src/repr/packed.rs
This PR adds an API to `CompactStr` to `reserve(additional: usize)`
=> feature: reserve API

compact_str/src/features/bytes.rs, compact_str/src/lib.rs, compact_str/src/repr/arc/mod.rs, compact_str/src/repr/heap.rs, compact_str/src/repr/mod.rs, compact_str/src/tests.rs
This PR adds more documentation and doc tests to the public API
=> chore: Add public documentation to CompactStr

.github/workflows/cross_platform.yml, .github/workflows/fuzz.yml
This PR runs some jobs on a self-hosted RaspberryPi to get coverage for more architectures
=> testing: Run some jobs on self-hosted ARMv7

README.md, compact_str/Cargo.toml
=> bump version to 0.3, update README

compact_str/src/repr/bytes.rs, compact_str/src/repr/heap.rs, compact_str/src/repr/inline.rs, compact_str/src/repr/iter.rs, compact_str/src/tests.rs
Just did a quick run through of all the docs to make sure they were up-to-date and make sure we're using intradoc links everywhere we can
=> chore: Update Docs

CHANGELOG.md, compact_str/Cargo.toml
Bump the version of `compact_str` to `v0.3.2`
=> version: 0.3.2

.github/workflows/ci.yml, .github/workflows/cross_platform.yml
Check number validity, i.e. forbid transmute(ptr, int).
=> Stricten miri, again

compact_str/src/lib.rs, compact_str/src/tests.rs
=> Optimize `From<Cow<'a, str>>` impl for `CompactStr`

bench/benches/compact_str.rs
Add some benchmarks for the `trait ToCompactStr`
=> perf: Benchmark ToCompactStr

CHANGELOG.md, README.md, compact_str/Cargo.toml
Bump the version of `compact_str` to `v0.4`
Thank you @Kijewski, @mcronce, and especially @CAD97 and @NobodyXu for all of your contributions!
=> version: 0.4

compact_str/src/lib.rs
=> Impl `AsRef<OsStr>` for `CompactString`

CHANGELOG.md
This PR just updates the "Upcoming" section in `CHANGELOG.md`
=> chore: Update the CHANGELOG

CHANGELOG.md, README.md, compact_str/Cargo.toml, compact_str/src/repr/heap.rs
Bump the version of `compact_str` to `v0.5`
Thank you @Nilstrieb, @NobodyXu, and @CAD97 for all of your contributions!
=> version: 0.5

.github/workflows/fuzz.yml, .gitignore, Cross.toml
This PR adds a workflow to CI that runs honggfuzz
=> fuzz: Add honggfuzz CI workflow

.github/workflows/fuzz.yml, fuzz/src/actions.rs, fuzz/src/creation.rs, fuzz/src/lib.rs
This PR adds more fuzzing coverage of various APIs. I used LLVM's code coverage tools to determine what APIs aren't currently covered by fuzzing, and started fuzzing them!
=> fuzz: Add more coverage for various APIs

compact_str/src/lib.rs, fuzz/src/actions.rs
=> Implement `truncate()`

compact_str/src/tests.rs
This PR adds some more unit testing for the `truncate(...)` API added in #132
=> test: Add more unit testing for truncate(...) API

compact_str/src/lib.rs, compact_str/src/repr/mod.rs, compact_str/src/tests.rs, fuzz/src/actions.rs
=> Implement insert() and insert_str()

compact_str/src/lib.rs, fuzz/src/actions.rs
=> Implement `clear()`

compact_str/src/lib.rs, fuzz/src/actions.rs
=> Implement `split_off()`

compact_str/src/lib.rs, compact_str/src/tests.rs
=> add AddAssign operator

.github/ISSUE_TEMPLATE.md, .github/workflows/fuzz.yml
This PR updates the fuzzing workflows to auto file an issue if there is a failure
=> ci: Auto file issue when fuzzing fails

compact_str/src/lib.rs, compact_str/src/repr/boxed/mod.rs, compact_str/src/repr/mod.rs, compact_str/src/tests.rs, fuzz/src/actions.rs
=> Implement `shrink_to()` and `shrink_to_fit()`

compact_str/src/lib.rs, fuzz/src/actions.rs
=> Implement `retain()`

compact_str/src/lib.rs, compact_str/src/tests.rs, fuzz/src/actions.rs
=> Implement `from_utf8_lossy()`

.github/workflows/fuzz.yml, compact_str/src/traits.rs
This PR disabled honggfuzz in CI because it appears to be broken currently
=> fuzz: fix honggfuzz

fuzz/src/actions.rs, fuzz/src/creation.rs
This PR refactors the fuzzing harness, adding creation options for UTF-16, UTF-16LE, UTF-16BE, and UTF-8, and moving some from `actions.rs` to `creation.rs`
=> fuzz: Update/refactor fuzzing actions

README.md, compact_str/src/lib.rs, compact_str/src/repr/iter.rs
This PR makes a few small changes to fix `clippy` and `rustdoc`
=> clippy: Fix Clippy and Rustdoc

compact_str/src/lib.rs
=> Implement `From<CompactString> for Cow<'_, str>`

compact_str/Cargo.toml
bumps the build portion of the version number from .0 to .1
=> version: 0.7.1

compact_str/src/lib.rs
=> feat: Implement `CompactString::repeat`

README.md, compact_str/Cargo.toml, compact_str/src/lib.rs, compact_str/src/repr/last_utf8_char.rs, compact_str/src/repr/mod.rs, compact_str/src/repr/smallvec.rs, compact_str/src/repr/static_str.rs, compact_str/src/tests.rs
=> feat: Support O(1) `CompactString::from_static_str`

compact_str/src/repr/capacity.rs
Removes the rayon dependency from a test
=> test: remove rayon dependency

compact_str/src/lib.rs, fuzz/Cargo.toml, fuzz/src/actions.rs, fuzz/src/creation.rs, fuzz/src/lib.rs
**_Work in progress_**
Fixes https://github.com/ParkMyCar/compact_str/issues/311
Blocked on https://github.com/ParkMyCar/compact_str/issues/313
=> fuzz: Add `from_static_str` as a `Creation` option in the fuzzing harness

examples/bytes/Cargo.toml, examples/macros/Cargo.toml, examples/serde/Cargo.toml, examples/traits/Cargo.toml
=> examples: Update to use v0.8.0-beta

compact_str/src/lib.rs, compact_str/src/tests.rs
Closes https://github.com/ParkMyCar/compact_str/issues/327
Each new impl has a corresponding test that requires that impl to be used for both long and short strings.
=> Add missing From impls that String has

compact_str/src/lib.rs
=> Minor code clean ups

compact_str/src/features/proptest.rs, compact_str/src/lib.rs, compact_str/src/repr/iter.rs, compact_str/src/tests.rs
=> fix: Remove explicit import of FromIterator

.github/workflows/fuzz.yml
There is a build failure which I need to debug, for now I'm disabling the scheduled runs so it stops filing issues
=> fuzz: Temporarily disable scheduled runs 

compact_str/Cargo.toml, compact_str/src/traits.rs
Fixes https://github.com/ParkMyCar/compact_str/issues/304
=> deps: Upgrade to `castaway v0.2.3`

CHANGELOG.md
=> release: prep CHANGELOG.md for v0.8.0

compact_str/Cargo.toml
Bumps the version of `compact_str` to v0.8.0 for release 🎉
Thank you to all of the folks that helped make this happen!
* @NobodyXu for PRs and reviews!
* @dragazo
* @SmnTin 
* @aobatact
* @Kijewski 
* @overlookmotel
* @tylerhawkes
=> version: 0.8.0

.github/workflows/ci.yml
Fixes the diesel example by making sure sqlite is installed
=> ci: Fix diesel examples

examples/diesel/Cargo.toml
=> example: bump version of `diesel` for RUSTSEC-2024-0365

compact_str/Cargo.toml
=> deps: bump `markup` to 0.15

examples/bytes/Cargo.toml, examples/diesel/Cargo.toml, examples/macros/Cargo.toml, examples/serde/Cargo.toml, examples/sqlx/Cargo.toml, examples/traits/Cargo.toml
=> examples: bump to `v0.9.0`
