compact_str/src/repr/discriminant.rs

We store `DiscriminantMask` in a union, so we need to repr-c it to
guarantee that type-punning works

add missing repr(C)

---

compact_str/src/lib.rs

The `Deref` one especially looks like it can be rather important

add missing inline

---

.github/workflows/ci.yml
compact_str/src/lib.rs

`#![deny(warnings)]` is an antipattern:
* it breaks downstream when compiler adds new warnings
* it has to be repeated for every crate (currenty, eg, tests don't deny warnings)
* it makes local development harder
A better approach is to deny warnings on CI

avoid incompatibility with future warnings hazard

---

compact_str/src/lib.rs
compact_str/src/tests.rs

Fixes #18
This PR implements the `std::str::FromStr` trait for `CompactStr`, where the error type is `core::convert::Infallible`. The ergonomics here aren't _great_ because despite making the error type "infallible" we still have to call unwrap. Once the never type, `!`, is stabilized, we can use that instead.

impl FromStr for CompactStr

---

compact_str/src/lib.rs
compact_str/src/repr/heap.rs
compact_str/src/repr/inline.rs
compact_str/src/repr/iter.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs

This PR implements the `FromIterator` trait for a common string types to make building `CompactStr`s more ergonomic

impl FromIterator<...> for CompactStr

---

CHANGELOG.md
README.md
compact_str/Cargo.toml

This PR bumps the version of CompactStr to `v0.2`. It now supports new features, and we move the MSRV back to 1.49 and edition 2018

Bump version to 0.2

---

.github/workflows/clippy.yml
.rustfmt.toml
compact_str/benches/compact_str.rs
compact_str/benches/comparison.rs
compact_str/src/lib.rs
compact_str/src/repr/discriminant.rs
compact_str/src/repr/heap.rs
compact_str/src/repr/inline.rs
compact_str/src/repr/iter.rs
compact_str/src/repr/mod.rs
compact_str/src/repr/packed.rs
compact_str/src/serde.rs
compact_str/src/tests.rs
compact_str/tests/alloc.rs
compact_str/tests/correctness.rs
tracing_alloc/src/lib.rs

This PR just adds a `.rustfmt.toml` to the root of the repo to customize some of the formatting. Unfortunately some of the rustfmt rules are unstable, so we need to use nightly to run rustfmt.
For future reference, you can run `rustfmt` by doing the following `cargo +nightly fmt`

Add formatting rules to .rustfmt.toml

---

.github/workflows/msrv.yml

As the title says, adds a CI workflow for the recently released rust v1.57

chore: Add rustc 1.57 to the MSRV CI workflow

---

.github/workflows/benchmarks.yml
.github/workflows/ci.yml

This new workflow just runs the benchmarks to make sure they're not broken. It does not actually report the results anywhere, that's still a TODO

chore: Add GitHub workflow that runs benchmarks

---

.github/workflows/ci.yml
compact_str/src/repr/heap/arc.rs
compact_str/src/tests.rs

This diff adds a CI workflow for [miri](https://github.com/rust-lang/miri), and makes a few small changes to skip proptest which can't currently run with miri, [issue](https://github.com/AltSysrq/proptest/issues/253).

testing: Add Miri to CI

---

.github/workflows/msrv.yml

This PR uses [`cargo-hack`](https://github.com/taiki-e/cargo-hack) to simplify the process of testing all compiler version since the MSRV (currently 1.49) and test all combinations of features (currently just `serde`) on these various compilers

testing: Use cargo-hack to test all compiler version > MSRV, and features

---

compact_str/src/lib.rs
compact_str/src/repr/heap/arc.rs
compact_str/src/repr/heap/mod.rs
compact_str/src/repr/inline.rs
compact_str/src/repr/mod.rs
compact_str/src/repr/packed.rs
compact_str/src/tests.rs

This PR adds an API to `CompactStr` that provides a mutable slice of the underlying buffer

feature: as_mut_slice API

---

compact_str/Cargo.toml
compact_str/src/asserts.rs
compact_str/src/lib.rs
compact_str/src/repr/arc/mod.rs
compact_str/src/repr/discriminant.rs
compact_str/src/repr/heap.rs
compact_str/src/repr/inline.rs
compact_str/src/repr/mod.rs
compact_str/src/repr/packed.rs

This PR vendors the two macros that are used from the [`static-assertions`](https://github.com/nvzqz/static-assertions-rs) crate. 
This removes what was the only required dependency from `compact_str` which has a marginal benefit in compile time and binary size, but now allows the library to be dependency free

vendor: static-assertions

---

compact_str/src/lib.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs
fuzz/src/lib.rs

This PR adds a `CompactStr::from_utf8(...)` API that is similar to `String::from_utf8(...)`. It also adds property based testing and fuzz testing for the new API

feature: Add from_utf8 API

---

.github/workflows/ci.yml
.github/workflows/clippy.yml
.github/workflows/cross_platform.yml
compact_str/src/asserts.rs
compact_str/src/features/bytes.rs
compact_str/src/lib.rs
compact_str/src/tests.rs

This PR does a few things:
1. Uses intra-doc links to (ideally) make the documentation easier to navigate and understand
2. Adds a workflow in CI that builds docs and denys warnings to make sure our links are up-to-date
3. Adds more documentation and a few more doc tests
4. Update docs after change to `BoxString` introduced in #56

docs: Improve and add workflow to CI

---

compact_str/src/lib.rs

Super small; just something I noticed when I went to benchmark replacing `smartstring` with `compact_str` in one of my projects :)
Kudos on the awesome crate!  It turns out that, at least in `imdb_async`, I deal with a _lot_ of strings that are 24 bytes in length.  Average performance seems to be approx. 10% faster with `compact_str` for that crate, presumably a result of increasing the allocation threshold from 23 to 24 bytes.

impl From<Cow<'_, str>> for CompactStr

---

CHANGELOG.md
compact_str/src/lib.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs

This PR implements `Extend<Cow<'_, str>>` for `CompactStr`

feature: impl Extend<Cow<'_, str>> for CompactStr

---

CHANGELOG.md
compact_str/Cargo.toml

This PR updates the version of `compact_str` to `v0.3.1` and updates the CHANGELOG accordingly

version: 0.3.1

---

compact_str/Cargo.toml
compact_str/src/features/bytes.rs
compact_str/src/repr/arc/mod.rs
compact_str/src/repr/boxed/mod.rs
compact_str/src/repr/inline.rs
compact_str/src/tests.rs

This PR uses the newer [`test-strategy`](https://github.com/frozenlib/test-strategy) crate, specifically the `#[proptest]` macro to, IMO, make the use a `proptest` a bit cleaner

chore: Cleanup use of proptest with test-strategy

---

compact_str/src/repr/mod.rs

This PR is a followup to #65 where `From<String>` and `From<Box<str>>` became `O(1)`. There we deferred inlining short heap strings to prevent the need to drop heap allocated memory. Here we inline short heap strings when resizing, since we need to drop the heap allocated buffer anyways.

perf: Inline short heap strings when resizing

---

README.md

https://github.com/bodil/smartstring/blob/master/CHANGELOG.md#100---2022-02-24
> ## [1.0.0] - 2022-02-24
> 
> ### CHANGED
> 
> -   `smartstring` now implements its own boxed string type rather than deferring directly to
>     `String`, so it no longer makes assumptions it shouldn't be making about the layout of the
>     `String` struct.
> 
>     This also allows us to organise the boxed struct in a way that will let us rely only on our
>     basic assumption that heap memory is word aligned on both big and little endian architectures.
>     The most immediate consequence of this is that `smartstring` will now compile on 32-bit big
>     endian architectures such as `mips`.
> 
>     We are now also explicitly allocating heap memory aligned for `u16` rather than `u8`, ensuring
>     the …

smartstring now no longer relies on `String` layout

---

bench/benches/compact_str.rs

Mainly, this pipes the input through `bench_with_input` so that it gets black box'd and it's a little more likely its not benefiting from being inlined.
Perf is within noise:
```
empty                   time:   [1.4388 ns 1.4422 ns 1.4464 ns]
CompactStr::new/0 chars time:   [1.6753 ns 1.6768 ns 1.6798 ns]
inline                  time:   [10.518 ns 10.521 ns 10.525 ns]
CompactStr::new/16 chars
time:   [8.2563 ns 8.2630 ns 8.2706 ns]
packed                  time:   [3.6113 ns 3.6150 ns 3.6203 ns]
CompactStr::new/24 chars
time:   [3.5912 ns 3.5919 ns 3.5926 ns]
heap                    time:   [54.525 ns 54.604 ns 54.699 ns]
CompactStr::new/59 chars
time:   [53.861 ns 54.034 ns 54.239 ns]
std_string              time:   [49.538 ns 49.601 ns 49.673 ns]
String::new/59 chars    time:   [47.855 …
```

Improve bench hygeine somewhat

---

compact_str/src/lib.rs
compact_str/src/tests.rs

This makes it possible to `write!()` into a CompactStr. This is useful if you know that the formatted string will be (most often) shorter than 24 bytes.

Implement fmt::Write for CompactStr

---

.github/workflows/ci.yml
.github/workflows/cross_platform.yml

Stricter provenance, yo
Basically, tells miri to pay more attention to stacked borrows w.r.t. raw pointers. (Also forbids int2ptr as a side effect, but if we can avoid it, that's a [good thing](https://github.com/rust-lang/rust/issues/95228).)

Tell miri to tag raw pointers

---

compact_str/src/repr/mod.rs

This PR is entirely based off of work originally done by @matklad in #7. I opened a new PR so I could make just a couple of tweaks
Here we're improving the performance of `Drop` when we have an inlined string which when running the `compact_str` benches locally I see ~8% improvement!

perf: Improve the performance of Repr::Drop for Inlined Variants

---

compact_str/src/tests.rs

There's an issue with formatting floats on PowerPC Little Endian 64-bit, for now we'll ignore the relevant assertions for this platform to keep the X-Plat CI target high signal

tests: Ignore failing test on PowerPC 64-bit

---

.github/workflows/ci.yml

I just realized the workflows that use `cargo-nextest` are completing so fast because it's not actually running any tests, [example](https://github.com/ParkMyCar/compact_str/runs/6240801199?check_suite_focus=true). For now I'm just removing nextest because it's not obvious why it's not actually testing anything

tests: Remove cargo-nextest because it wasn't running anything

---

.github/workflows/ci.yml
.github/workflows/msrv.yml

Removed in #86 because the tests weren't running anything, but solution was commented on that PR so re-adding to CI using the suggested [GitHub Action](https://nexte.st/book/pre-built-binaries.html#using-nextest-in-github-actions). We also add some more caching, specifically for the MSRV workflow, which cuts runtime from ~20 minutes to ~9 minutes

tests: Re-add cargo-nextest

---

.github/workflows/ci.yml
.github/workflows/fuzz.yml
.github/workflows/msrv.yml

For the MSRV workflow we separate the toolchain cache from the build cache because we don't need to invalidate the toolchains if our `Cargo.toml` changes, like we do the build cache

tests: Separate toolchain cache from build cache

---

.github/workflows/fuzz.yml

Just use the `afl` compiled using the nightly toolchain installed.

Fix afl jobs in workflow `fuzz`: Do not cache `~/.cargo/bin`

---

bench/benches/compact_str.rs

This PR updates the benchmarks for `ToCompactStr` to include `u128` and fixes the benchmark for `isize`

bench: Update ToCompactStr Benchmarks

---

README.md
bench/benches/apis.rs
bench/benches/compact_str.rs
bench/benches/comparison.rs
compact_str/src/features/bytes.rs
compact_str/src/features/serde.rs
compact_str/src/lib.rs
compact_str/src/repr/boxed/mod.rs
compact_str/src/repr/iter.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs
compact_str/src/traits.rs
fuzz/src/lib.rs

This PR renames `CompactStr` to `CompactString`
Some feedback I've received is using the "str" suffix isn't great because it suggests that a `CompactStr` doesn't own the underlying string, just like a `&str`. We change the suffix to "String" to fix this and improve the understanding.
We also add a type alias of `CompactStr` so existing crates will continue to work, albeit with a deprecation warning. This breaking change will go out with v0.4 to prevent suddenly introducing warnings in projects that depend on `compact_str`

refactor: Rename CompactStr to CompactString

---

examples/bytes/Cargo.toml
examples/bytes/src/main.rs
examples/serde/Cargo.toml
examples/serde/src/main.rs

This PR updates all of the examples to use `compact_str v0.4`

examples: Update compact_str to 0.4

---

compact_str/src/lib.rs
compact_str/src/macros.rs

So that users can format any args into `CompactString` similar to how they can do it using [`std::format!`](https://doc.rust-lang.org/std/macro.format.html).

Add macro_rules `format_compact!`

---

compact_str/src/lib.rs
compact_str/src/repr/mod.rs

For the naive case, e.g. when there are no arguments to format `write!(&mut compact_string, "hello_world")`, appends the string directly to the referenced `CompactString` to avoid the machinery of `fmt::Arguments`
Original implementation in #76

perf: Optimize fmt::Write

---

CHANGELOG.md
compact_str/src/lib.rs
compact_str/src/traits.rs
fuzz/src/lib.rs

This PR introduces a new trait `CompactStringExt` which provides two methods:
1. `join_compact(seperator: impl AsRef<str>)`
2. `concat_compact()`
And then `CompactStringExt` is implemented for all types that implement `IntoIterartor<Item = AsRef<str>>`.

feat: CompactStringExt trait

---

.github/workflows/cross_platform.yml
.github/workflows/fuzz.yml
.github/workflows/msrv.yml

Today if you change just the `README.md` or `CHANGELOG.md` it kicks off the entire test suite, which is unnecessary. This PR updates the CI workflows so they only trigger when certain paths change

ci: Only run workflows when certain paths change

---

CHANGELOG.md
compact_str/src/lib.rs

In `v0.4` we renamed `CompactStr` to `CompactString`, and then added a type alias of `CompactStr` so folks could upgrade to `v0.4` without issue. We marked the type alias as deprecated though, and said it would be removed in `v0.5`. To prep for a `v0.5` release we're removing the type alias here

chore: Remove CompactStr type alias

---

Cargo.toml
compact_str/src/features/bytes.rs
compact_str/src/repr/boxed/mod.rs
compact_str/src/repr/inline.rs
compact_str/src/repr/traits.rs
compact_str/src/tests.rs
compact_str/src/traits.rs
fuzz/Cargo.toml

This PR renames all tests that use `proptest` from `test_*` to `proptest_*` just to make our naming a bit more explicit.
It also gets rid of our patched dependencies:
1. `arbitrary`, we previously used a patched version to include a fix for fuzzing large input data on 32-bit machines. That fix shipped in `arbitrary 1.1.1`
2. `test-strategy`, we previously used a patched version that was Rust 2018, but now that we bumped the MSRV we can depend on the published crate

test: Cleanup test names and dependencies

---

CHANGELOG.md
Cargo.toml
compact_str/src/repr/inline.rs
examples/macros/Cargo.toml
examples/macros/src/main.rs
examples/traits/Cargo.toml
examples/traits/src/main.rs

This PR does a number of small things:
1. Removes a bounds check, originally proposed in #9 
2. Adds examples for the `ToCompactString` and `CompactStringExt` traits, and the `format_compact!(...)` macro
3. Cleans up code in `InlineString` now that the MSRV has been bumped to 1.57

cleanup and examples: Removes bounds check, adds more examples, removes const_panic hack

---

.github/workflows/ci.yml
examples/bytes/Cargo.toml
examples/macros/Cargo.toml
examples/serde/Cargo.toml
examples/traits/Cargo.toml

This PR updates the examples to use `compact_str v0.5`, and updates CI to include the `macros` and `traits` examples

examples: Update examples to use compact_str v0.5

---

compact_str/src/lib.rs
compact_str/src/repr/boxed/mod.rs
compact_str/src/repr/heap.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs

Tests added and run under `miri`. Ensures that no reallocation/copy of already-boxed strings happens in a round-trip, with the address, length, and capacity remaining stable.
Closes #117

feat: add impl From<CompactString> for String

---

compact_str/src/lib.rs
fuzz/src/lib.rs

`String::as_mut_str()` returns a mutable slice of its contents. This PR adds the same method to CompactString.
The method is safe, because no safe operation on `&mut str` can result in a broken UTF-8 string.

Add `as_mut_str()` method

---

compact_str/src/lib.rs
fuzz/src/lib.rs

This PR implements `CompactString::replace_range()` to work the same way as the method in String of the same name.
It uses DerefMut as implemented in #124, but it could easily be written to work without it if #124 is not accepted.

Implement `replace_range()`

---

.github/workflows/ci.yml
.github/workflows/clippy.yml
.github/workflows/cross_platform.yml
.github/workflows/fuzz.yml
.github/workflows/msrv.yml
Cross.toml

While looking the Github Actions workflows for [`honggfuzz-rs`](https://github.com/rust-fuzz/honggfuzz-rs/blob/master/.github/workflows/rust.yml) I saw they set the `CARGO_TERM_COLOR` env variable to `always`. Seems like a good idea to make CI a little prettier/easier to read

ci: Add the CARGO_TERM_COLOR env variable

---

compact_str/src/tests.rs
fuzz/src/creation.rs

This PR changes the `CollectChars` creation step in the fuzzing harness to generate smaller strings, and instead we'll test larger strings with proptest.
Generating large strings in the fuzzing harness reduced our executions per-second from ~3,500 to ~30, which is not great.

fuzz: Reduce size of strings CollectChars generates

---

compact_str/src/lib.rs
compact_str/src/tests.rs

Implementing `Add<CompactString> for String` breaks `String + &String`, as long as `compact_str` is used somewhere in your current crate. Specifically this code won't compile:
```
use compact_str;
fn main() {
println!("{}", "Hello".to_string() + &(" World".to_string()));
}
```
This isn't good! This has to do with Rust's current trait resolver and is a known issue https://github.com/rust-lang/rust/issues/77143
To fix this, we remove `impl Add<CompactString> for String`. You can still add `CompactString` to `String`, you just need to take a reference to it, then the `impl Add<&str> for String` kicks in.
We also remove a lot of `impl Add<...> for CompactString`, leaving just `impl Add<&str> for CompactString`, which allows us to add _more_ string types than we currently can, e.g. `&Box<str>` …

fix/feat: Change the existing Add<...> impls

---

.github/workflows/msrv.yml
compact_str/Cargo.toml
compact_str/src/features/arbitrary.rs
compact_str/src/features/mod.rs
compact_str/src/features/proptest.rs
compact_str/src/features/quickcheck.rs

This PR implements the `Arbitrary` trait from the [`arbitrary`](https://github.com/rust-fuzz/arbitrary), [`proptest`](https://github.com/AltSysrq/proptest), and [`quickcheck`](https://github.com/BurntSushi/quickcheck) crates. It then makes those crates optional dependencies.
This makes it easier for folks to include a `CompactString` in their types, and then use randomized testing to cover those types

feat: Implement the Arbitrary trait from various crate

---

.github/workflows/cross_platform.yml
.github/workflows/fuzz.yml

This PR comments out the two jobs that use the ARMv7 self hosted runner. The runner appears to be broken and I can't access it at the moment to fix it. Will re-enable soon

ci: Disable X-Plat and Fuzz workflow that runs on ARMv7 (Raspberry Pi)

---

compact_str/src/lib.rs

This PR updates the doc test for `CompactString::clear()` to assert capacity doesn't change

test: update doc test for CompactString::clear()

---

compact_str/src/lib.rs
fuzz/src/actions.rs

Makes `replace_range()` reusable, and closes #134.

Implement `drain()`

---

.github/workflows/cross_platform.yml
.github/workflows/fuzz.yml

this PR re-enables the ARMv7 workflows after I restarted the self hosted runner

ci: re-enable the ARMv7 workflows

---

compact_str/src/lib.rs
compact_str/src/repr/mod.rs

It's simply encoding the character as a UTF-8 sequence, then appending the sequence. So `push()` can simply call `push_str()`.

Deduplicate `CompactString::push()`

---

compact_str/src/repr/boxed/capacity.rs
compact_str/src/tests.rs
fuzz/Cargo.toml
fuzz/src/bin/debug.rs

When we changed `CompactString` to have the same size as `Option<CompactString>`, we made the `HEAP_MASK` discriminant `254`, which made our `CAPACITY_IS_ON_THE_HEAP` flag `[254, 254, 254, 254]`.
When you encode `16711422` in little endian bytes, it's `[254, 254, 254, 0]`, and when we append our `HEAP_MASK` we get `[254, 254, 254, 254]`. So when we'd try to create a `CompactString` with size `16711422`, we'd incorrectly identify the capacity as being on the heap, when it's really inline.
To fix this I updated the `CAPACITY_IS_ON_THE_HEAP` `[255, 255, 255, ..., HEAP_MASK]`, which is the correct value. I added a test to assert all values for `Capacity` successfully round trip for 32-bit architectures.

fix: Test case discovered by AFL

---

compact_str/src/repr/boxed/capacity.rs
compact_str/src/tests.rs

* fix: Bug when trying to create a CompactString with capacity of 16711422 on 32-bit arches
* Fixed the underlying bug, which was related to the change in HEAP_MASK
* Add debug.rs binary to repro single failing fuzz cases
* Add unit test with comment to repro the exact failure
* ignore all capacity values test in miri
Backport of: https://github.com/ParkMyCar/compact_str/pull/161

backport(v0.5): Test case discovered by AFL (#161)

---

compact_str/Cargo.toml
compact_str/src/repr/boxed/capacity.rs
compact_str/src/repr/boxed/inner.rs
compact_str/src/repr/boxed/mod.rs

This PR implements `realloc(size)` for `BoxString`, which is the underlying heap representation of a `CompactString`

perf: Implement realloc for BoxString

---

.github/workflows/cross_platform.yml
.github/workflows/fuzz.yml
.github/workflows/msrv.yml

Like the title says, don't trigger certain workflows when it's only `README.md` or `CHANGELOG.md` files that change.

ci: Ignore certain workflows when only README.md or CHANGELOG.md are changed

---

CHANGELOG.md
compact_str/Cargo.toml
compact_str/src/lib.rs
compact_str/src/tests.rs
fuzz/src/creation.rs

Implements from_utf16 for `CompactString` and adds doc tests, unit tests, proptests, and updates our fuzzing harness.
Fixes #135

feat: Implement CompactString::from_utf16

---

compact_str/src/lib.rs
compact_str/src/tests.rs
fuzz/src/actions.rs

* add unit tests
* add doc tests
* add prop tests
* add to fuzzing harness
Fixes #141

feat: Implement CompactString::remove()

---

compact_str/src/lib.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs
fuzz/src/creation.rs

This PR adds `CompactString::from_utf8_unchecked(...)`, which has the same behaviors as [`String::from_utf8_unchecked(...)`](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_unchecked). We also add unit tests (which get Miri coverage), proptests, and update our fuzzing harness.
Fixes: #138

feat: from_utf8_unchecked API

---

compact_str/src/lib.rs
compact_str/src/macros.rs
compact_str/src/tests.rs

So that `format_compact!()` still works if the user shadows
`format_args!()`, or uses the library in a `#![no_implicit_prelude]`
context.

Macro hygiene: use re-exported `format_args!()`

---

compact_str/Cargo.toml
compact_str/src/features/rkyv.rs
compact_str/src/features/serde.rs

After merging #208 I realized we didn't have any unit tests for our `serde` integration. This PR adds a proptest for the newly added `rkyv` integration, and a unit test and proptest for the `serde` integration.

tests: Add proptests for rkyv and serde

---

compact_str/src/lib.rs
compact_str/src/tests.rs
fuzz/src/actions.rs

Implement `from_utf16ne_lossy` and `from_utf16be_lossy`

---

compact_str/src/lib.rs
compact_str/src/tests.rs
fuzz/src/creation.rs

This PR implements the `from_utf16_lossy` API for `CompactString`. It also adds doc tests, proptests, and fuzzing for the new method

feat: implement from_utf16_lossy API

---

fuzz/src/actions.rs

This PR adds a new action to the fuzzing harness that clones the "control" and "compact" string and drops the originals

fuzz: Add new CloneAndDrop action

---

compact_str/src/lib.rs

Based on the docs from the stdlib, when calling [`align_to`](https://doc.rust-lang.org/std/primitive.slice.html#method.align_to), it's possible for the entirety of the data to be returned in the prefix, or suffix slices:
> This method splits the slice into three distinct slices: prefix, correctly aligned middle slice of a new type, and the suffix slice. The method may make the middle slice the greatest length possible for a given type and input slice, but only your algorithm’s performance should depend on that, not its correctness. It is permissible for all of the input data to be returned as the prefix or suffix slice.
This PR updates our use of `.align_to` to make sure the both the prefix slice and suffix slice are empty, thus guaranteeing the middle slice contains all of our data

fix: make sure suffix data when calling .align_to is empty

---

CHANGELOG.md
compact_str/Cargo.toml

Bumps the version of `compact_str` to `v0.6.0`, and updates the CHANLGELOG.md

version: 0.6

---

compact_str/Cargo.toml

The last build on docs.rs failed:
<https://docs.rs/crate/compact_str/0.6.0/builds/615366>.
To use proptest, you have to either enable "std" or "alloc". Because
this project uses features in "std", we can enable "proptest/std". We
know that the support is there.
I cannot tell why the bug does not manifest in the CI, which checks the
documentation creation. On my own system it works without this PR, too.

Enable "proptest/std" feature

---

compact_str/src/repr/inline.rs

It seem like some optimization step goes berserk if you copy a byte
slice from start to end. The while-loop is partially unrolled which
results in an excessively long, extremely cache unfriendly code.
If you copy the string in the reverse direction, starting with the last
byte, the optimizer understands the pattern, and uses `memcpy()`, which
is a sane decision.
If you only use `CompactString::new_inline()` in a `const` context, the
difference does not matter. But if you use it for runtime code, the
difference is enormous. Valid use cases for `new_inline()` in a
non-const context include `const` function that may be also useful in a
dynamic context.

Copy inline string reversed

---

.github/workflows/msrv.yml
examples/bytes/Cargo.toml
examples/macros/Cargo.toml
examples/serde/Cargo.toml
examples/traits/Cargo.toml

* update MSRV workflow to exclude arbitrary since the MSRV of the latest build version is Rust 1.63
* update the examples to use compact_str v0.6

chore: Fix CI, update examples

---

compact_str/src/lib.rs

Needed this for something earlier tonight and noticed it wasn't implemented - one tiny gap in `CompactString`'s public API compared to std `String`'s

impl AsRef<[u8]> for CompactString

---

.github/workflows/fuzz.yml
fuzz/Cargo.toml

This PR updates the honggfuzz dependency to use https://github.com/ParkMyCar/honggfuzz-rs, which updates the `honggfuzz` submodule to the latest master. This fixes a bug which prevents running honggfuzz on 32-bit arches.
I've opened a PR to upstream this change, https://github.com/rust-fuzz/honggfuzz-rs/pull/75

deps: Update honggfuzz to rely on fork

---

.github/workflows/cross_platform.yml

The Raspberry Pi I was using as an ARMv7 runner is currently offline, so for now I'm commenting out any workflows that depend on it

ci: Disable ARMv7 Workflow

---

compact_str/src/lib.rs

The documentation should state expects instead of excepts in my opinion.

Fix a typo in documentation

---

.github/workflows/msrv.yml
compact_str/Cargo.toml

Recently [`proptest`](https://github.com/proptest-rs/proptest) bumped their version from `1` to `1.1` and included in that change was a new dependency on [`unarray`](https://github.com/cameron1024/unarray) which has an MSRV of `1.60`, which is greater than `compact_str`s MSRV of `1.57`. This caused the MSRV check in CI to fail since we enable the `proptest` feature in the check.
This PR removes `proptest` from the MSRV check with a comment as to why we removed it. Note: we still check for compatibility of the `proptest` feature as part of the `feature_powerset` job
Related to https://github.com/proptest-rs/proptest/issues/300

ci: remove proptest from MSRV check

---

compact_str/src/tests.rs

Originally fixed in #228, adding a test now to make sure we never regress here
Fixes #226

test: Add test to assert CompactStr -> std::borrow::Cow<'_, str>

---

fuzz/Cargo.toml
fuzz/src/actions.rs
fuzz/src/lib.rs

This PR updates the fuzzing harness to reduce the number of actions run for a given `Scenario`. The idea is that running 3,000 actions isn't any more "interesting" than running 1,000 actions, it just takes 3x longer. Instead if we cap the number of actions that we run, we'll get more of an opportunity to explore the different combinations of creation + actions, which gives us better coverage of the code.
Specifically this PR changes the fuzzing harness so we generate a seed with a `Scenario` and using that seed we pick a random number based on a Skewed Normal distribution, and only run up to that number of actions. Based on testing, the distribution has the approximate metrics:
`min: 0`
`median: 1000`
`max: 3500`
Because the seed is included with a `Scenario`, it allows us to be …

fuzz: Reduce the number of actions run for a given Scenario

---

compact_str/src/repr/mod.rs
compact_str/src/tests.rs
fuzz/src/actions.rs

This PR implements a performance improvement for `Clone`-ing a `CompactString`. If the capacity of the original `CompactString` is "inline-able", i.e. it's <= 24 bytes, then the new `CompactString` we return will be inlined.
Also included in this PR is a change to the fuzzing harness to assert we inline `CompactString`s when possible, and to limit the number of actions per run, which allows to improve the total number of runs.

perf: Inline strings when Clone-ing

---

compact_str/Cargo.toml

This PR changes the version of castaway we depend on from `0.2.1` to `0.2`. Using `0.2` is more generic and allows us to automatically get patches which theoretically is good :)

deps: Use castaway 0.2

---

compact_str/src/features/proptest.rs
compact_str/src/lib.rs
compact_str/src/repr/iter.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs
fuzz/src/creation.rs

Currently when converting from a `String` to a `CompactString` using `From<String>` (also for `Box<str>`) we wouldn't inline short strings, this was to avoid needing to de-allocate the original `String`. After some feedback collected in #227 we realized while this was performant, it's not what most users expect to happen.
This PR updates the implementation of `From<String>` and `From<Box<str>>` to inline short strings, and it adds a new API `CompactStr::from_string_buffer`, which retains the current behavior of always re-using the underlying buffer. Note, in #254 we implemented inline-ing during `Clone`, so even if you use `from_string_buffer`, future short strings should get inlined.
Fixes #227

api: Update From<String> and From<Box<str>> to eagerly inline

---

compact_str/src/repr/mod.rs
fuzz/src/actions.rs

In #254 we began inlining `CompactString`s when `Clone`-ing, if the **capacity** of the `CompactString` was less than `MAX_SIZE`. This made sure we retained any additional capacity a user may have allocated.
During some experimentation though, I realized `String` truncates capacity during clone, [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=65cc3239a32936f17ff7f81cffd44860).
As such this PR updates the eager inlining during `Clone` to instead be based on the source `CompactString`'s **length**, which. This allows us to more frequently inline strings, and follows the same behavior as `String`.

api: On Clone, eagerly inline based on length not capacity

---

compact_str/Cargo.toml
compact_str/src/features/mod.rs
compact_str/src/features/smallvec.rs
compact_str/src/repr/inline.rs
compact_str/src/repr/mod.rs
compact_str/src/repr/smallvec.rs

This PR adds a new API `CompactString::into_bytes` which consumes a `CompactString`, returning a byte vector, just like the [`String::into_bytes`](https://doc.rust-lang.org/std/string/struct.String.html#method.into_bytes) method.
A difference though is `CompactString::into_bytes` returns a [`SmallVec`](https://docs.rs/smallvec/latest/smallvec/struct.SmallVec.html) which allows us to avoid needing to allocate, by re-using the underlying buffer from the `CompactString`

api: Add CompactString::into_bytes

---

compact_str/Cargo.toml

This PR just bumps the version of `compact_str` to `0.7`

branch start, bump version to v0.7

---

compact_str/src/repr/iter.rs
compact_str/src/repr/mod.rs
compact_str/src/repr/smallvec.rs

**Context**
A `CompactString` internally wraps a `Repr`, and a `Repr` is an abstraction over an `InlineBuffer` or a `HeapBuffer`. We determine which kind of buffer we have by checking our discriminant. We used to define a `Repr` as a [`union`](https://doc.rust-lang.org/std/keyword.union.html) but have since switched to defining it as a normal struct. In order to switch between a `Repr` and a `HeapBuffer` or `InlineBuffer` we need to transmute/reinterpret the structs.
**Changes**
This PR replaces the `mem::transmute(...)` calls we had sprinkled in code with one of six new methods:
1. `fn from_heap(...)`
2. `fn from_inline(...)`
3. `unsafe fn as_heap(...)`
4. `unsafe fn as_mut_heap(...)`
5. `unsafe fn as_inline(...)`
6. `unsafe fn as_mut_inline(...)`
In the two safe functions we document …

refactor: Reduce or wrap unsafe code

---

fuzz/Cargo.toml
fuzz/src/actions.rs

This PR updates the fuzzing harness to test the new `CompactString::into_bytes` method that was added in #258

fuzz: Update harness to test into_bytes

---

CHANGELOG.md
compact_str/src/features/smallvec.rs
compact_str/src/lib.rs
compact_str/src/tests.rs

I realized this recently that `CompactString::as_ptr` took a mutable reference to self (aka `&mut self`), when all it really needs is a normal reference (aka `&self`). This PR updates the API to make that change

refactor: Change CompactString::as_ptr to take &self

---

.github/workflows/ci.yml
.github/workflows/fuzz.yml

This PR adds a new workflow to CI that runs our tests with the [`randomize-layout`](https://github.com/rust-lang/compiler-team/issues/457) `rustc` flag enabled, and enables the flag for our fuzzing runs

ci: Randomize Layout in CI

---

examples/bytes/Cargo.toml
examples/macros/Cargo.toml
examples/serde/Cargo.toml
examples/traits/Cargo.toml

This PR just updates the examples to the most recent version of `compact_str`

examples, update to v0.7

---

.github/workflows/msrv.yml
bench/Cargo.toml
compact_str/Cargo.toml
compact_str/src/repr/mod.rs

In the `as_slice()` method, we didn't need to take a ref to `pointer` or `length`.

refactor: Remove unneeded code

---

README.md
compact_str/src/repr/last_utf8_char.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs

Before this change there is one nieche: The last byte could never have the value `255`. With this change all values in the range `217..=255` cannot occur in the last byte. Actually, these values were already impossible before, but we did not tell the compiler about it.

Open up more niches

---

.github/workflows/cross_platform.yml

Something in CI broke and now all of the builds that use `cross` don't pass. I'll investigate this further, but for now we'll just disable these steps.

ci: Disable steps that use cross

---

compact_str/src/repr/mod.rs

This PR depends on #276.
Using the fact that `LastUtf8Char::Heap` comes exactly after the last inline length value, we can simplify the calculation a bit.
The resulting code on amd64:
```asm
mov    0x8(%rdi),%rax
movzbl 0x17(%rdi),%ecx
add    $0xffffffffffffff40,%rcx
cmp    $0x18,%rcx
cmovae %rax,%rcx
mov    $0x18,%eax
cmovbe %rcx,%rax
ret
```

Simplify `Repr::len() `

---

compact_str/src/lib.rs

Enable converting a `str` to lower/upper case and get a `CompactString` directly for inline storage.

feat: Impl `CompactString::from_str_to_{lower, upper}case`

---

compact_str/src/repr/capacity.rs

In #276 I changed the value of the byte that tells if a string is stored on the heap, but I forgot to update the test for `Capacity`.
The compiler does not quite understand what we are doing in `Capacity::new()` and `Capacity::as_usize()`. Working on `usize` instead of `[u8; _]` allows the compiler to keep everything in registers instead of having to store the value on the stack to modify it.
Before:
```asm
Capacity::new:
movabsq	$72057594037927935, %rcx
andq	%rdi, %rcx
movabsq	$-2882303761517117440, %rax
orq	%rcx, %rax
retq
Capacity::as_usize:
movzwl	4(%rdi), %eax
movzbl	6(%rdi), %ecx
shll	$16, %ecx
orl	%eax, %ecx
shlq	$32, %rcx
movl	(%rdi), %eax
orq	%rcx, %rax
retq
```
After:
```asm
Capacity::new:
movabsq	$-2882303761517117440, %rax
orq	%rdi, %rax
retq
Capacity::as_usize:
movabsq …
```

Fix and optimize `Capacity`

---

.github/workflows/msrv.yml
CHANGELOG.md
README.md

This PR bumps the MSRV from `1.57` to `1.59`. There are some new features we want to use and given 1.59 was released almost 18 months ago, I think this version is sufficiently old.

MSRV: Bump to 1.59

---

.github/workflows/nostd.yml
compact_str/Cargo.toml
compact_str/src/features/bytes.rs
compact_str/src/features/markup.rs
compact_str/src/features/proptest.rs
compact_str/src/features/quickcheck.rs
compact_str/src/features/rkyv.rs
compact_str/src/features/serde.rs
compact_str/src/features/smallvec.rs
compact_str/src/lib.rs
compact_str/src/repr/bytes.rs
compact_str/src/repr/heap.rs
compact_str/src/repr/inline.rs
compact_str/src/repr/iter.rs
compact_str/src/repr/last_utf8_char.rs
compact_str/src/repr/mod.rs
compact_str/src/repr/num.rs
compact_str/src/repr/traits.rs
compact_str/src/tests.rs
compact_str/src/traits.rs
compact_str/src/unicode_data.rs

I have a compiler/interpreter project I'm developing for embedded systems, and this crate looks perfect for saving a ton of heap space and gaining locality for my many symbol tables. The only issue is that it needs to be `no_std` and #29 was closed a long time ago. So I've gone ahead and redone that work here.
It's pretty much all just a switch from `std` to `core` or `alloc` versions of things, plus a new (default) feature flag called `std` that enables a few small things like operations on `OsString` and the like.
The new version passes all test cases in standard mode, successfully builds in no-std mode, and miri has no issues with anything.

support no_std

---

compact_str/src/repr/mod.rs
compact_str/src/traits.rs

After merging #287 specialization for `String` in the impl of `ToString` broke due to an issue in `castaway`. That issue has been fixed and we're just waiting for a release. In the meantime we'll disable the specialization.

fix: Remove String specialization

---

.github/workflows/ci.yml
.github/workflows/cross_platform.yml
.github/workflows/msrv.yml
Cargo.toml
compact_str/Cargo.toml
compact_str/src/repr/capacity.rs
compact_str/src/repr/inline.rs
compact_str/src/tests.rs

This PR excludes the `compact_str` crate from the workspace to help relax the dependency resolution. It also cleans up the MSRV workflow now that dependency resolution is relaxed.

cleanup: Exclude `compact_str` from workspace cleanup MSRV workflow

---

.github/workflows/cross_platform.yml
compact_str/src/repr/mod.rs

This PR re-enables the CI workflows that target multiple different architectures using `cross`.

ci: Re-add multiple arch workflows

---

compact_str/src/repr/mod.rs

This change optimizes `Repr::as_slice()`, which is used e.g. in `CompactStr::as_str()`.
This is done by replacing `last_byte == HEAP_MASK || last_byte == STATIC_STR_MASK` with `last_byte >= HEAP_MASK`, because we know that there can be no other case.
Also is `self.last_byte()` is called multiple times instead of using the "cached" value. This lets the optimzer decide whether to access the same variable again or use a register. And reassigning the variable `pointer` for the `>= HEAP_MASK` case is done immediately. Both changes together reduce the "percived" register pressure of the compiler, so it will be more eager to omit branches.
Generated assembly before:
```asm
0000000000000000 <compact_str::deref_compact_string>:
0: 48 89 f9             mov    %rdi,%rcx
3: 8a 47 17             mov …
```

Remove branches from `Repr::as_slice()`

---

compact_str/src/tests.rs
fuzz/src/actions.rs
fuzz/src/creation.rs
fuzz/src/lib.rs

Adds `proptest` and fuzzing coverage for the `repeat(...)` function.
Note: this PR is split into two commits:
1. The implementation of testing
2. Update to the fuzz corpus

test: Add proptest fuzz coverage for repeat

---

.github/workflows/clippy.yml
Cargo.toml
compact_str/src/repr/heap.rs
compact_str/src/repr/inline.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs
fuzz/src/lib.rs

This PR starts running clippy on tests, runs fmt and clippy on `compact_str`, which accidentally regressed when we removed `compact_str` from the workspace.

lint: Run clippy on tests

---

compact_str/Cargo.toml

Given the amount of user facing improvements that have been made to `compact_str` recently, e.g. representing `&'static str` in a `CompactString` and `no_std` support, I want to get a release out. 
Hard blocker before we can release this version:
* https://github.com/ParkMyCar/compact_str/issues/313
But there are a few blockers I want to solve before "promoting" to a full release, specifically:
* https://github.com/ParkMyCar/compact_str/issues/304
* https://github.com/ParkMyCar/compact_str/issues/310
* https://github.com/ParkMyCar/compact_str/issues/311

version: 0.8.0-beta

---

.github/workflows/benchmarks.yml
.github/workflows/ci.yml
.github/workflows/clippy.yml
.github/workflows/cross_platform.yml
.github/workflows/fuzz.yml
.github/workflows/msrv.yml
.github/workflows/nostd.yml

Fixed #280 and fixed #279
also:
- Bump `actions/checkout` to v4
- use `taiki-e/install-action` to install any binary crates
- use `Swatinem/rust-cache@v2` for caching
- use `strategy` to avoid similar/duplicate jobs
- pass `--no-deps` to `cargo-clippy`
- Use `cargo-nextest` for `randomize-layout`
- Run doc test in job `test`
- Use `cargo-nextest` to speedup `miri`
- Run `cargo-check` instead of `cross-build` in `nostd.yml` since
there's no need for `cross`

Improve CI: Rm use of deprecated actions

---

.github/workflows/cross_platform.yml
.github/workflows/msrv.yml
compact_str/src/repr/mod.rs

With some recent PRs we hit some merge skews that prevented a test from compiling, this PR fixes those issues. It also bumps the MSRV CI workflow to 1.60, suddenly when running in 1.59 we get the following error:
```
$ cargo +1.59 check --no-default-features                                                                                                                         [±fix/merge-skew ●]
Updating crates.io index
error: failed to select a version for `rkyv`.
... required by package `compact_str v0.8.0-beta (/Users/parker/Development/compact_str/compact_str)`
versions that meet the requirements `^0.7` are: 0.7.41, 0.7.40, 0.7.39, 0.7.38, 0.7.37, 0.7.36, 0.7.35, 0.7.34, 0.7.33, 0.7.32, 0.7.31, 0.7.30, 0.7.29, 0.7.28, 0.7.27, 0.7.26, 0.7.25, 0.7.24, 0.7.23, 0.7.22, 0.7.21, 0.7.20, …
```

fix: Merge skew and MSRV workflow

---

compact_str/src/lib.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs

Before:
```asm
0000000000000000 <<compact_str::CompactString>::is_empty>:
0:   48 8b 77 08             mov    0x8(%rdi),%rsi
4:   0f b6 57 17             movzbl 0x17(%rdi),%edx
8:   48 8d 8a 40 ff ff ff    lea    -0xc0(%rdx),%rcx
f:   48 83 f9 18             cmp    $0x18,%rcx
13:   b8 18 00 00 00          mov    $0x18,%eax
18:   48 0f 42 c1             cmovb  %rcx,%rax
1c:   48 81 fa d8 00 00 00    cmp    $0xd8,%rdx
23:   48 0f 43 c6             cmovae %rsi,%rax
27:   48 85 c0                test   %rax,%rax
2a:   0f 94 c0                sete   %al
2d:   c3                      ret
```
After
```asm
0000000000000000 <<compact_str::CompactString>::is_empty>:
0:   48 8b 57 08             mov    0x8(%rdi),%rdx
4:   0f b6 4f 17             movzbl 0x17(%rdi),%ecx
8:   48 8d 81 40 ff ff ff …
```

Simplify `is_empty()`

---

compact_str/src/lib.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs

This way short static strings have better cache locality, too.

Inline short static strings

---

compact_str/src/repr/heap.rs
compact_str/src/repr/inline.rs
compact_str/src/repr/static_str.rs

Fixes #353.
I also added assertions that `HeapBuffer` and `StaticStr` have same alignment as `Repr`.

Align InlineBuffer same as Repr

---

compact_str/src/lib.rs
compact_str/src/repr/mod.rs
compact_str/src/repr/smallvec.rs
compact_str/src/repr/traits.rs
compact_str/src/tests.rs
compact_str/src/traits.rs
examples/diesel/src/lib.rs
examples/sqlx/src/lib.rs
fuzz/src/creation.rs

Closes #322.
Please see #322 for an explanation.

Add `const_new()`; remove `new_inline()` and `from_static_str()`

---

compact_str/src/lib.rs
compact_str/src/repr/mod.rs
compact_str/src/tests.rs

This PR adds some more impls of PartialEq between `String`, `str`, and `CompactString`. 
Fixes https://github.com/ParkMyCar/compact_str/issues/372

fix: More `PartialEq` impls

---

compact_str/src/lib.rs

https://github.com/ParkMyCar/compact_str/pull/336 removed these APIs in favor of `CompactString::const_new()`, I still think that's a great idea but want to retain these APIs for one release, marked as deprecated.

api: Re-add `new_inline()` and `from_static_str()` as deprecated

---

compact_str/Cargo.toml
compact_str/src/features/borsh.rs
compact_str/src/features/mod.rs

This PR adds support for the `borsh` serialization library, similar to that of `serde` and `rkyv`.

Add `borsh` support

---

.github/workflows/msrv.yml
.github/workflows/release.yml
compact_str/README.md

Changes the MSRV check to not enable features which is too flaky, it also updates the MSRV to 1.60. Technically the MSRV was already `1.60` because of optional features using `dep:...` which isn't supported in Rust 1.59

fix: MSRV check and change MSRV to 1.60

---

compact_str/src/lib.rs

The MSRV is now 1.60 so this tag is unnecessary

cleanup: Remove `rustversion(since(1.60))` tag

---

compact_str/README.md

Updates the README to call out `no_std` support and `O(1)` creation from `&'static str`
Fixes https://github.com/ParkMyCar/compact_str/issues/310

docs: Update README

---

compact_str/src/lib.rs

Add `assert_eq_size!` assertion.

Document CompactString has niches

---

compact_str/src/lib.rs
compact_str/src/repr/bytes.rs
compact_str/src/repr/capacity.rs
compact_str/src/repr/heap.rs
compact_str/src/repr/inline.rs
compact_str/src/repr/last_utf8_char.rs
compact_str/src/repr/mod.rs
compact_str/src/repr/smallvec.rs
compact_str/src/repr/static_str.rs
compact_str/src/tests.rs
compact_str/src/unicode_data.rs

When reading sources, make it more obvious what is public API, and
what is internals.
Also `pub(crate)` prevents exposing internals accidentally.

pub(crate) private code

---

compact_str/src/features/sqlx.rs

This impl is necessary to use `CompactString` in newtypes

impl sqlx::postgres::PgHasArrayType

---

compact_str/src/repr/mod.rs
compact_str/src/tests.rs

This PR removes the following code from `Repr::from_utf8_unchecked`:
https://github.com/ParkMyCar/compact_str/blob/d4798639c24cacf528770d83e8842336b79fbc39/compact_str/src/repr/mod.rs#L126-L137
In my opinion, this code should be removed for 2 reasons:
1. It is part of the safety contract for `from_utf8_unchecked` that `buf` is the bytes of a valid UTF8 string. This check penalizes users who follow the safety contract (which everyone should), in order to support users who don't (and therefore have opted in to UB).
2. This check alone is not enough to avoid UB anyway. If `buf` ends with the first byte of a multi-byte Unicode character, for example calling `.as_str().chars().collect::<Vec<char>>()` on the resulting `CompactString` will cause an out of bounds read.

Remove invalid UTF8 check from `Repr::from_utf8_unchecked`

---

compact_str/README.md
compact_str/src/repr/capacity.rs
compact_str/src/repr/last_utf8_char.rs
compact_str/src/repr/mod.rs

As suggested during the discussion on [HackerNews](https://news.ycombinator.com/item?id=41338776)
* Update the name of `LastByteUtf8` to `LastByte` since it represents more than just the possible values of the last byte of a UTF-8 char.
* Update the README to include more similar crates

docs: Update some naming and README

---

.github/workflows/ci.yml
compact_str/Cargo.toml
compact_str/src/features/sqlx.rs
examples/sqlx/Cargo.toml
examples/sqlx/src/lib.rs

As it says on the tin! Upgrades the `sqlx` dependency to `v0.8`, this picks up the fix for [RUSTSEC-2024-0363](https://rustsec.org/advisories/RUSTSEC-2024-0363.html).
Fixes https://github.com/ParkMyCar/compact_str/issues/407

deps: upgrade to `sqlx v0.8`

---

compact_str/Cargo.toml
compact_str/src/features/rkyv.rs

As it says on the tin! Upgrades to `rkyv v0.8`

deps: upgrade to `rkyv v0.8`

---

compact_str/src/lib.rs
compact_str/src/tests.rs

The current implementation of `CompactString::retain` breaks `len` if the `predicate` passed as `retain` method argument panics during iteration.
Please see: https://github.com/rust-lang/rust/issues/78498
For this problem, I did:
- Added test `alloc::String` have.
- Fix `retain` method implementation.

fix: retain not set len if predicate panics

---

compact_str/src/lib.rs
compact_str/src/repr/capacity.rs
compact_str/src/tests.rs

* In the function `fn as_bytes` in `impl CompactString`, there is an redundant slicing (with a `self.len()` call) which is unnecessary after the update c95edd5.
* This crate has documented that for 64-bit architectures the capacity will be always inlined. So the logic of `is_heap` can be replaced with directly returning `false` to reduce some code generation.

Some slightly performance & style updates

---

.github/workflows/ci.yml
.github/workflows/clippy.yml
compact_str/src/repr/mod.rs
compact_str/src/traits.rs
fuzz/src/creation.rs

Fixes https://github.com/ParkMyCar/compact_str/issues/412
This is a possibly breaking change.
Previously `CompactStringExt` was (more or less) implemented for any type `C` where a `&C` implemented `IntoIterator<Item = &str>`. This worked well for when you wanted to join `Vec`s or slices, but would result in a confusing compile time error when you tried to join an iterator of some type, e.g. when you tried to do `values.iter().map(|val| val.trim()).join_compact(",")`.
There is a [blanket impl for `IntoIterator`](https://doc.rust-lang.org/src/core/iter/traits/collect.rs.html#351) for all types that implement `Iterator`, but our trait bound required some _reference_ of a type to implement `IntoIterator` which wasn't covered by this blanket impl.

feat: tweak the `CompactStringExt` trait so `join_compact` and `concat_compact` work better

---

compact_str/Cargo.toml
compact_str/src/features/mod.rs
compact_str/src/features/zeroize.rs
compact_str/src/repr/mod.rs
fuzz/Cargo.toml
fuzz/src/actions.rs

This PR implements the `zeroize::Zeroize` trait for a `CompactString` deriving the implementation from the `zeroize` crate. It also adds proptest and fuzz testing coverage

feat: Add support for `zeroize::Zeroize`

---

compact_str/src/features/borsh.rs

Fixes using the `borsch` feature in `no_std` contexts but qualifying the `vec!` macro

fix: The `borsch` feature with no-std

---

compact_str/src/lib.rs

fix: delete methods that are documented as deprecated in `v0.9.0`

---

CHANGELOG.md
compact_str/Cargo.toml
examples/diesel/Cargo.toml
examples/sqlx/Cargo.toml

Bump to `v0.9.0`!
* Bump the version in `Cargo.toml`
* Update the `CHANGELOG.md`

version: 0.9.0
